import type { Metadata } from 'next'
import './globals.css'

import { montserrat } from './fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

import Footer from './components/footer/footer'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
